vizionlink-objs := vizionlink_host.o vizionlink_cam.o

obj-$(CONFIG_VIDEO_VIZION_LINK) += vizionlink.o

# all:
# 	make ARCH=arm64 CROSS_COMPILE=/home/jerry/l4t-gcc/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu- -C /home/jerry/nvidia/nvidia_sdk/JetPack_4.6_Linux_JETSON_XAVIER_NX_TARGETS/Linux_for_Tegra/source/public/build M=$(PWD) modules

# clean:
# 	make ARCH=arm64 CROSS_COMPILE=/home/jerry/l4t-gcc/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu- -C /home/jerry/nvidia/nvidia_sdk/JetPack_4.6_Linux_JETSON_XAVIER_NX_TARGETS/Linux_for_Tegra/source/public/build M=$(PWD) clean