ifdef CONFIG_MEDIA_SUPPORT
max96792a-objs := max96792a_mux.o
max96724-objs := max96724_mux.o
max96712_tn-objs := max96712_mux.o
max96716a-objs := max96716a_mux.o
max9296a-objs := max9296a_mux.o
max96717-objs := max96717_mux.o
obj-m += max96792a.o
obj-m += max96724.o
obj-m += max96712_tn.o
obj-m += max96716a.o
obj-m += max9296a.o
obj-m += max96717.o
endif
