ifdef CONFIG_MEDIA_SUPPORT
max_serdes_all_tn-objs := max_ser.o max_des.o max_serdes.o
obj-m += max_serdes_all_tn.o
obj-m += max96717_tn.o
obj-m += max96724_tn.o
obj-m += max96712_tn.o
obj-m += max9296a_tn.o
obj-m += max96716a_tn.o

endif
