tevi_ar0521-objs = main.o otp_flash.o
obj-$(CONFIG_VIDEO_TEVI_AR0521) += tevi_ar0521.o

# all:
# 	make ARCH=arm64 CROSS_COMPILE=/home/jerry/l4t-gcc/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu- -C /home/jerry/nvidia/nvidia_sdk/JetPack_4.6_Linux_JETSON_NANO_TARGETS/Linux_for_Tegra/source/public/build M=$(PWD) modules

# clean:
# 	make ARCH=arm64 CROSS_COMPILE=/home/jerry/l4t-gcc/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu- -C /home/jerry/nvidia/nvidia_sdk/JetPack_4.6_Linux_JETSON_NANO_TARGETS/Linux_for_Tegra/source/public/build M=$(PWD) clean
