subdir-ccflags-y += -Werror

ccflags-y += -I$(srctree)/drivers/media/platform/tegra
ccflags-y += -I$(srctree)/drivers/video/tegra/camera

obj-$(CONFIG_VIDEO_VIZION_LINK) += vizionlink/
obj-$(CONFIG_VIDEO_TEVI_AR0144) += tevi_ar0144/
obj-$(CONFIG_VIDEO_TEVI_AP1302) += tevi_ap1302/
obj-$(CONFIG_VIDEO_TEVI_OV5640) += tevi_ov5640/
